# Same as '--format'
# Default is 'table'
format: json

# Same as '--report' (available with 'trivy k8s')
# Default is all
report: all


# Same as '--dependency-tree'
# Default is false
dependency-tree: true

# Same as '--list-all-pkgs'
# Default is false
list-all-pkgs: false

# Same as '--ignorefile'
# Default is '.trivyignore'
ignorefile: .trivyignore


# Same as '--exit-code'
# Default is 0
exit-code: 0


# Same as '--severity'
# Default is all severities
severity:
  - UNKNOWN
  - LOW
  - MEDIUM
  - HIGH
  - CRITICAL
