name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker (se necessário para seu projeto)
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.0/trivy_0.29.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.0_Linux-64bit.deb

      - name: Run Trivy Scan
        run: |
          # Se estiver escaneando uma imagem Docker
          trivy image your-image-name:latest --format json --output trivy-report.json

          # Se estiver escaneando arquivos locais (por exemplo, código fonte ou dependências)
          trivy fs . --format json --output trivy-report.json

      - name: Check if report exists
        run: |
          if [ -f trivy-report.json ]; then
            echo "Trivy report exists!"
          else
            echo "Trivy report not found!"
            exit 1
          fi

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: ./trivy-report.json  # Certifique-se de que o caminho esteja correto
